
levellocks = [0,1,1,1,1,1,1,1,1,1,1,1]


level1 = {"num":1,"map": 
["g             g                                      c c c c                                   g",  
 "g             g  f                                gbbbbbbbbbbbbg                               g",  
 "g             g                       t T                                                      g",  
 "g             gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg        gl         g",  
 "g                                         g                                         ggl        g",  
 "g                                         g                                         gggl       g",  
 "g                                         g                                         ggggl      g",  
 "g                                         g    t       cccccccccccc                 gggggl     g",  
 "g                                  c  gggbgggggggggggggggggggggggggggggggggggggggbbbggggggbggggg",  
 "g                               c  g  ggg     c     c     c     c    c    c     c     c    ggggg",  
 "g                               g     gggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",  
 "g       P          t T       gC       gggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",  
 "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",  
 "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],  
 "ground image":"beach.png",
  "background image":"beachbackground.png",
         "music":"beachtheme.ogg",
          "decor":["palmtree1.png","palmtree2.png","beachbush.png"]}
level2 = {"num":2,"map":
 ["                                                                                                                          ",
  "gg                                                                                                                      gg",
  "gg                                                                      gbbbbbg       g                        f        gg",
  "gg                                rgb                                                 g                                 gg",
  "gg                               rggb        gl                 ggggg                 g            rgb    ggggggg       gg",
  "gg                              rgggb        ggl        c c c                         g           rggb                  gg",
  "gg        ggg      ggg         rggggb        gggl      ggggggg                        g          rgggb                  gg",
  "gg P                        t rggggg         ggggl     TC   tC          TC      C     g         rgggg        cccc       gg",
  "gggggggSSSSSSSSSSSSSSSSSSSSggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"beach.png",
  "background image":"beachbackground.png",
         "music":"beachtheme.ogg",
          "decor":["palmtree1.png","palmtree2.png","beachbush.png"] }
level3 = {"num":3,"map":
 [
  "g                                                                                                                  ggg",
  "g                                                                                                                  ggg",
  "g                                                                                                                  ggg",
  "g                                                                                                                  ggg",
  "g                                             gbbbbbbbbg                                                           ggg",
  "g                                   gggg                                                                           ggg",
  "g     cccc     cccc     cccc    J                                                          ggg         f           ggg",
  "g  P        a        a       gggggg                                                 ggg                            ggg",
  "g ggg      ggg      ggg      gggggg                              ggggggg     ggg                     ggggg         ggg",
  "gSSSSSSSSSSSSSSSSSSSSSSSSSSSSggggggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"beach.png",
  "background image":"beachbackground.png",
         "music":"beachtheme.ogg",
          "decor":["palmtree1.png","palmtree2.png","beachbush.png"] }

level4 = {"num":4,"map":
 ["                                                                                                                      ",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                     gggg      ggggggg       gg                     g",
  "g                                                                                             gg                     g",
  "g                 8     cccc                                     ggg                          gg                     g",
  "g               ggg          ggg                   8    ggggg    gggbbb                       gg                     g",
  "g         ggg   gggbbb       ggg                 ggg             ggg                          gg           f         g",
  "g  TtP          ggg     C    ggg   a    ggg      ggg             ggg        G                 gg    t   T     t    T g",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"grassland_ground.png",
  "background image":"grasslandbg.png",
   "music":"grasslandtheme.ogg",
          "decor":["oaktree1.png","oaktree2.png","bush.png"]}

level5 = {"num":5,"map":
 ["                                                                                                                      ",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "gP                                                               g                                                   g",
  "gggl                             gggg       gggg       gggg      g                                                   g",
  "gggggl                                   J         J             g                            B             f        g",
  "gggggggl         gggg                                            g              Gggg                                 g",
  "gggggggggggg              ggggggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggg  8       8   gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"grassland_ground.png",
  "background image":"grasslandbg.png",
   "music":"grasslandtheme.ogg",
          "decor":["oaktree1.png","oaktree2.png","bush.png"]}

level6 = {"num":6,"map":
 ["                                                                                                                      ",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggg     B      gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "g                                                                                                                    g",
  "g              gggg                          ggggggggggggg                                c c                        g",
  "g              gggg                             gggggggggg                          ggggg     c                      g",
  "g             gggggggg            gbbbbbg       gggggggggg               ggggg      ggggg       c                    g",
  "g             ggggggggggg         g             gggggggggg     ggggg                ggggg       c   f                g",
  "gP          p gggggggggggggg      g            8gggggggggg                          ggggg       c                    g",
  "ggggSSSSSSSgggggggggggggggggSSSSSSggggggggggggggggggggggggSSSSSSSSSSSSSSSSSSSSSSSSSSgggggSSSSSSSgggggSSSSSSSSSSSSSSSSg",
  "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"grassland_ground.png",
  "background image":"grasslandbg.png",
   "music":"grasslandtheme.ogg",
          "decor":["oaktree1.png","oaktree2.png","bush.png"]}

level7 = {"num":7 ,"map":
 ["gg                                                                                                                                      ",
  "gg                                                                                                                                      ",
  "gg                                                                                                                                      ",
  "gg                                                                                                                                      ",
  "gg                                                                                                                                      ",
  "gg                                                                                                                                      ",
  "gg                                                                                                                                      g",
  "gg                                                                                                                                      g",
  "gg                                                                                                                                     lg",
  "gg                                                                                    B                                                gg",
  "gg                                            8                                      c c c                                             gg",
  "gg                             aaaa        gggg                                     ggggggg                                            gg",
  "gg                           gggggggg                 B        gggg                                                           cc cc    gg",
  "gg                 8          gg  gg                                         gggg                                            ccccccc   gg",
  "gg           gggggggggg       gg  gg                 gggggg                                                f                  ccccc    gg",
  "gg                            gg  gg                                  gggg               T                                     ccc     gg",
  "gg P    T     c c c c c   t   gg  gg        aa                J               t       gggggggg        t  T   a T                c      gg",
  "gggggggggggggggggggggggggggggggg  gg      ggggggg                           gggggg                   gggggggggggggg        gggggggggggggg",
  "gg   gg   gg   gg   gg   gg   gg  ggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSgg",
  "gg   gg   gg   gg   gg   gg   gg  ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"snowy_ground.png",
  "background image":"snowbg.png",
   "music":"icetheme.ogg",
          "decor":["pinetree1.png","pinetree2.png","snowbush.png"]}

level8 = {"num":8 ,"map":
 ["                                                                                                                                                ",
  "g                                                                                                                                                ",
  "g                                                                                                                                              gg",
  "g                                                                                                                                              gg",
  "g                                                                                                                                              gg",
  "g                                                                                                                                              gg",
  "g                                                                                                                                              gg",
  "g                                                                                                                                              gg",
  "gT Pt t                                                                                                                                        gg",
  "ggggggg                                                                                                                                        gg",
  "g                                                                                                                                              gg",
  "g                                                                                        8                                                     gg",
  "g                                                    cc                                ggg                                    f                 g",
  "g                   8                                                                                                                           g",
  "g                 ggg                              g    g                    p                                           ggggggg                g",
  "g                                                  g    g                ggggg                               gggggg                             g",
  "g                                                rgg    ggl         J         J                                                                 g",
  "g   W    ccccc      T        W         T  t    rgggg    ggggl     a    t    T  a t     t         rggggl            G  c  c  c   cC           W  g",
  "ggggggggggggggggggggggggggggggggggggggggggggggggggggSSSSggggggggggggggggggggggggggggggSSSSSSSSggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"snowy_ground.png",
  "background image":"snowbg.png",
   "music":"icetheme.ogg",
          "decor":["pinetree1.png","pinetree2.png","snowbush.png"]}

level9 = {"num":9 ,"map":
 ["                                                                                                                                              ",
  "gl                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg  P                                                                                                                                            ",
  "gggggl                                                                                           f                                             ",
  "ggggggggl    c                                                                                                                                  ",
  "gggggggggg   c                                                                                                                                   ",
  "gggggggggg   c               g     Q                 8                        Q        g         g                                              ",
  "gggggggggg   c               gbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg    g                                                  ",
  "gggggggggg     c             gb                                                                                                                 ",
  "gggggggggg     c             gb                                                                                   g                             ",
  "ggggggggggggl  c            ggb                                                                                   g                             ",
  "gggggggggggggl  c                g  g  g   gg                                                                     g                             ",
  "ggggggggggggggg  c             SSSSSSSSSSSS ggg      a 8                                                          g                             ",
  "ggggggggggggggg  c             gggggggggggggggggggggggggggggggg   SgS  gggggggggggggggg    b  b  b b   b   b      g                             ",
  "ggggggggggggggg   c                                               ggg                                      b      gg                            ",
  "ggggggggggggggg    c                                                                                       b      gg                            ",
  "gggggggggggggggl                                                                            b   b   bb  bb b      gg                            ",
  "ggggggggggggggggl                    a8                    a8                    8a         b                     gg                            ",
  "gggggggggggggggggggl               gggggg                gggggg                ggggg        b                     gg                            ",
  "ggggggggggggggggggggl             gggggggg             ggggggggg              ggggggg       b                     gg                            ",
  "ggggggggggggggggggggggggl    Q   ggggggggggg   Q     ggggggggggggg     Q    ggggggggggg     b           T        hgg                            ",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"snowy_ground.png",
  "background image":"snowbg.png",
   "music":"icetheme.ogg",
          "decor":["pinetree1.png","pinetree2.png","snowbush.png"]}

level10 = {"num":10 ,"map":
 ["gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggg    c Tc  c  c  c  c  c  c  c  c  ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggg           T        T             ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggg    g          W              g   ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggg                                 gggggggggggggggggggggggggggg                                gggggggggggggggggggggggggggggggggggggggggg",
  "ggggggg       ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg                ggggggggggggggggggggggggggggggggggggggggggg",
  "gggggg      gggggggggggggggggggggggg                               M             gggg     c c          ggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggg          ggggggggggggggg                                               gggggggg    c                 g          T       ggggggggggggg",
  "gggggggggggggggggg                                                                gggggggg    c                 g                     gggggggggg",
  "gggggggggggggggggggggggggggggggggggg                   cccccc                  ggggggggggg     c                g                    ggggggggggg",
  "gggggggg                     gggggggg                                           gggggggggg                      gg     JJJJJ       gggggggggggg",
  "ggggg           ccccccc      ggggggggggggggg    a     gSSgSSSg    t             ggggggggggg               f     gggg    ccccccc       ggggggggggg",
  "ggggg   gggggggggggggggggggg ggggggggggggggggggggggggggggggggggggggggggggg              ggggg                   c  gg   ccccccc      gggggggggggg",
  "ggggggg           ggggggggggcgg            c   c            ggggggggggggggggggggggggggg  ggggggggg              gg     ccccccc       ggggggggggg",
  "gggggggggg ccccc   ggggggggg gg   gggggggggggggg     T            M                      ggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggg  ggggggggcgggg   c c   gggggg            c c        T          gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggg               ggggggggg ggggggggggg  gggggg                               ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggg P       ggggggggggggggg             ggggggg      t        W   t   gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"cave.png",
  "background image":"cavebg.png",
   "music":"cavetheme.ogg",
          "decor":["cavetree1.png","cavetree2.png","cavebush.png"] }

level11 = {"num":11 ,"map":
 ["gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gg         ggggggggggggg                                                                                                                      gg",
  "gg   P     gggggggg      J                ccccccccccccccccc c  c   ccc cccccccccccc                                                           gg",
  "ggbbbbbbbbbgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggbb                                                      gg",
  "gg         ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg                                                        gg",
  "gg    J    ggggggg           gggggggggggggggggggggggggggggggggggggggggggggggggggggggggbbbbbb                                                  gg",
  "ggg       gggggggg               T            M      T         M              M      T        g                             J                 gg",
  "gggg    ggggggggggg                     T                                                                                                     gg",
  "ggggg  gggggggggggggh                                                                           g                                       f     gg",
  "gggg cc   gggggggggggggg                 p                                                          g                                         gg",
  "gg   cc     ggggggggggggggggg        ggggggg  gg  g  ggg g ggg g ggg g gg g  gg                                                               gg",
  "gg   cc        c  c c c cM          gggg                                     ggg                   ggg g  gg  ggggg  g gggg g g gg  g gggggggggg",
  "ggg  bb                          gggggg                                     gggg             g gg                                             gg",
  "ggSSSSSSSg          t     t    ggggggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSggggggg    W  ggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSgg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"cave.png",
  "background image":"cavebg.png",
   "music":"cavetheme.ogg",
          "decor":["cavetree1.png","cavetree2.png","cavebush.png"] }


level12 = {"num":12 ,"map":
 ["gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                        E       gg",
  "gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                   t  gggggggggggg",
  "gg               ggggggggggggggggggg",
  "gg  W    t     ggggggggggggggggggggg",
  "gggggggggggggbb                   gg",
  "ggggggggggg           J  JJ       gg",
  "gggggggggggggggggg              gggg",
  "gggggggggggggggggggggg        gggggg",
  "ggggggggggggggggggggggggggbbgggggggg",
  "ggS   SgS   SgS       SgS    SgS Sgg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "ggS SgS       SgS      SgS       Sgg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "ggS      SgS      SgS       SgS  Sgg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "gg                                gg",
  "ggbbgggggggggggggggggggggggggggggggg",
  "gg             M               M  gg",
  "ggbb                              gg",
  "gg                                gg",
  "ggbb                              gg",
  "gg    gSSgSSgSSgSSgSSgSSg         gg",
  "ggggggggggggggggggggggggggggggbbbbgg",
  "gg                                gg",
  "ggbbgggggggggggggggggggggggggggggggg",
  "gg                           gg   gg",
  "ggbb            J          gbggbgbgg",
  "gg                         g gg g gg",
  "ggbb                       gbggbgbgg",
  "gg         J               g    g gg",
  "gggggggggggggggggggggggggggggggggbgg",
  "ggM                    M          gg",
  "gg                               bgg",
  "gg                                gg",
  "gggggggggbbbbggggggggggggggggggggggg",
  "gg W                              gg",
  "ggggggggggggggggggggggggggggbbbbgggg",
  "gg W                              gg",
  "gggggggggggggggbbbbbgggggggggggggggg",
  "gg W                              gg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "gg W                              gg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "gg W                              gg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "ggl                               gg",
  "gggl                              gg",
  "gggggl      P           a     aa  gg",
  "gggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggg"],
 "ground image":"cave.png",
  "background image":"cavebg.png",
   "music":"cavetheme.ogg",
          "decor":["cavetree1.png","cavetree2.png","cavebush.png"] }




